#%RAML 1.0 Library

annotationTypes:

  resource:
    type: string

  resource-type:
    type: string

  resource-collection:
    type: string

  resource-property:
    type: string

  resource-link:
    type: string
